const S = [
{g:"Iran 🇮🇷",a:"Ebi",t:"Shab-e Niloofari"},{g:"Iran 🇮🇷",a:"Siavash Ghomeyshi",t:"Jazireh"},
{g:"Iran 🇮🇷",a:"Faramarz Aslani",t:"Age Ye Rooz"},{g:"Iran 🇮🇷",a:"Dariush",t:"Shab az Mahtab Sar Mire"},
{g:"Iran 🇮🇷",a:"Mohsen Chavoshi",t:"Ghahveye Ghajari"},{g:"Iran 🇮🇷",a:"Mohsen Yeganeh",t:"Beyte Akhar"},
{g:"Iran 🇮🇷",a:"Ehaam",t:"Bezan Baran"},{g:"Iran 🇮🇷",a:"Hayedeh",t:"Siah Cheshmoon"},
{g:"Iran 🇮🇷",a:"Homayoun Shajarian",t:"Koli"},{g:"Iran 🇮🇷",a:"Sirvan Khosravi",t:"Ghabe Akse Khali"},
{g:"Your picks ✦",a:"Annika",t:"Luk Mig Ind"},{g:"Your picks ✦",a:"Twenty One Pilots",t:"The Line (Arcane)"},
{g:"Your picks ✦",a:"Imagine Dragons",t:"Natural"},{g:"Your picks ✦",a:"Imagine Dragons",t:"Radioactive"},
{g:"Your picks ✦",a:"Lady Gaga",t:"Always Remember Us This Way"},{g:"Pakistan 🇵🇰",a:"Nusrat Fateh Ali Khan",t:"Allah Hoo"},
{g:"Pakistan 🇵🇰",a:"Nusrat Fateh Ali Khan",t:"Ye Jo Halka Halka Suroor Hai"},{g:"Pakistan 🇵🇰",a:"Mehdi Hassan",t:"Ranjish Hi Sahi"},
{g:"Pakistan 🇵🇰",a:"Ghulam Ali",t:"Chupke Chupke Raat Din"},{g:"Pakistan 🇵🇰",a:"Abida Parveen",t:"Tere Ishq Nachaya"},
{g:"Pakistan 🇵🇰",a:"Farida Khanum",t:"Aaj Jaan Ki Zid Na Karo"},{g:"Pakistan 🇵🇰",a:"Atif Aslam",t:"Tajdar-e Haram (Coke Studio)"},
{g:"Pakistan 🇵🇰",a:"Rahat Fateh Ali Khan & Momina",t:"Afreen Afreen (Coke Studio)"},{g:"Pakistan 🇵🇰",a:"Vital Signs",t:"Dil Dil Pakistan"},
{g:"Pakistan 🇵🇰",a:"Nazia Hassan",t:"Aap Jaisa Koi"},{g:"India 🇮🇳",a:"A.R. Rahman",t:"Kun Faya Kun"},
{g:"India 🇮🇳",a:"A.R. Rahman",t:"Tere Bina"},{g:"India 🇮🇳",a:"Lata Mangeshkar",t:"Lag Ja Gale"},
{g:"India 🇮🇳",a:"Kishore Kumar",t:"O Mere Dil Ke Chain"},{g:"India 🇮🇳",a:"Jagjit Singh",t:"Hothon Se Chhu Lo Tum"},
{g:"India 🇮🇳",a:"Shreya Ghoshal",t:"Teri Ore"},{g:"India 🇮🇳",a:"Shankar Mahadevan",t:"Breathless"},
{g:"India 🇮🇳",a:"Sukhwinder Singh",t:"Chaiyya Chaiyya"},{g:"India 🇮🇳",a:"Asha Bhosle",t:"Piya Tu Ab To Aaja"},
{g:"India 🇮🇳",a:"A.R. Rahman",t:"Agar Tum Saath Ho"},{g:"Turkey 🇹🇷",a:"Tarkan",t:"Kuzu Kuzu"},
{g:"Turkey 🇹🇷",a:"Şebnem Ferah",t:"Sil Baştan"},{g:"Turkey 🇹🇷",a:"Teoman",t:"Paramparça"},
{g:"Turkey 🇹🇷",a:"Duman",t:"Her Şeyi Yak"},{g:"Turkey 🇹🇷",a:"Sezen Aksu",t:"Kutlama"},
{g:"Turkey 🇹🇷",a:"Pinhani",t:"Beni Al"},{g:"Turkey 🇹🇷",a:"Müslüm Gürses",t:"Sen Benim Şarkılarımsın"},
{g:"Armenia 🇦🇲",a:"Sirusho",t:"PreGomesh"},{g:"Armenia 🇦🇲",a:"Aram Khachaturian",t:"Adagio from Spartacus"},
{g:"Armenia 🇦🇲",a:"Charles Aznavour",t:"La Bohème"},{g:"Armenia 🇦🇲",a:"Aram Mp3",t:"Not Alone"},
{g:"Armenia 🇦🇲",a:"Iveta Mukuchyan",t:"LoveWave"},{g:"Armenia 🇦🇲",a:"Tigran Hamasyan",t:"Levitation 21"},
{g:"Armenia 🇦🇲",a:"Djivan Gasparyan",t:"Melancholy"},{g:"Armenia 🇦🇲",a:"Maléna",t:"Qami"},
{g:"Georgia 🇬🇪",a:"Nino Katamadze",t:"Blue Smoke"},{g:"Georgia 🇬🇪",a:"Katie Melua",t:"Nine Million Bicycles"},
{g:"Georgia 🇬🇪",a:"Sopho Nizharadze",t:"Shine"},{g:"Kazakhstan 🇰🇿",a:"Dimash Kudaibergen",t:"SOS"},
{g:"Kazakhstan 🇰🇿",a:"Dimash Kudaibergen",t:"Daididau"},{g:"Kazakhstan 🇰🇿",a:"Zhanar Dugalova",t:"Izin Korem"},
{g:"Kazakhstan 🇰🇿",a:"MuzArt",t:"Senimen"},{g:"Kazakhstan 🇰🇿",a:"Dimash Kudaibergen",t:"Konyldym"},
{g:"Japan 🇯🇵",a:"Kenshi Yonezu",t:"Lemon"},{g:"Japan 🇯🇵",a:"Official HIGE DANdism",t:"Pretender"},
{g:"Japan 🇯🇵",a:"Hibari Misora",t:"Kawa no Nagare no Yō ni"},{g:"Japan 🇯🇵",a:"Ryuichi Sakamoto",t:"Merry Christmas Mr. Lawrence"},
{g:"Japan 🇯🇵",a:"Ryo Fukui",t:"Early Summer"},{g:"Japan 🇯🇵",a:"YOASOBI",t:"Yoru ni Kakeru"},
{g:"Japan 🇯🇵",a:"Utada Hikaru",t:"First Love"},{g:"Japan 🇯🇵",a:"X Japan",t:"Endless Rain"},
{g:"South Korea 🇰🇷",a:"Kim Bum-soo",t:"Bo Go Ship Da (I Miss You)"},{g:"South Korea 🇰🇷",a:"Lee Sun-hee",t:"Fate (인연)"},
{g:"South Korea 🇰🇷",a:"Im Jae-beom",t:"As This Night Passes"},{g:"South Korea 🇰🇷",a:"Cho Yong-pil",t:"Come Back to Busan Port"},
{g:"South Korea 🇰🇷",a:"Shin Joong Hyun",t:"Jasmine"},{g:"South Korea 🇰🇷",a:"Lee Moon-sae",t:"Gwanghwamun Sonata"},
{g:"South Korea 🇰🇷",a:"Younha",t:"Event Horizon"},{g:"South Korea 🇰🇷",a:"IU",t:"Through the Night"},
{g:"South Korea 🇰🇷",a:"Position",t:"I Love You"},{g:"China 🇨🇳",a:"Teresa Teng",t:"The Moon Represents My Heart"},
{g:"China 🇨🇳",a:"Jay Chou",t:"Qing Hua Ci"},{g:"China 🇨🇳",a:"Faye Wong",t:"Legend (传奇)"},
{g:"China 🇨🇳",a:"Jonathan Lee",t:"Hill (山丘)"},{g:"China 🇨🇳",a:"Eason Chan",t:"Ten Years (十年)"},
{g:"China 🇨🇳",a:"Cui Jian",t:"Nothing to My Name (一无所有)"},{g:"Philippines 🇵🇭",a:"Freddie Aguilar",t:"Anak"},
{g:"Philippines 🇵🇭",a:"Eraserheads",t:"Ang Huling El Bimbo"},{g:"Philippines 🇵🇭",a:"Rivermaya",t:"214"},
{g:"Philippines 🇵🇭",a:"Bamboo",t:"Noypi"},{g:"Philippines 🇵🇭",a:"Sharon Cuneta",t:"Kahit Maputi Na Ang Buhok Ko"},
{g:"Philippines 🇵🇭",a:"Rey Valera",t:"Kung Kailangan Mo Ako"},{g:"Philippines 🇵🇭",a:"Regine Velasquez",t:"On the Wings of Love"},
{g:"Philippines 🇵🇭",a:"Basil Valdez",t:"Ngayon at Kailanman"},{g:"Philippines 🇵🇭",a:"Lea Salonga",t:"Reflection"},
{g:"Philippines 🇵🇭",a:"VST Company",t:"Awitin Mo at Isasayaw Ko"},{g:"Nigeria 🇳🇬",a:"Wizkid",t:"Essence"},
{g:"Nigeria 🇳🇬",a:"Tems",t:"Free Mind"},{g:"Nigeria 🇳🇬",a:"Burna Boy",t:"Last Last"},
{g:"UK 🇬🇧",a:"The Beatles",t:"A Day in the Life"},{g:"UK 🇬🇧",a:"David Bowie",t:"Life on Mars?"},
{g:"UK 🇬🇧",a:"Queen",t:"Bohemian Rhapsody"},{g:"UK 🇬🇧",a:"Pink Floyd",t:"Wish You Were Here"},
{g:"UK 🇬🇧",a:"Kate Bush",t:"This Woman's Work"},{g:"UK 🇬🇧",a:"Led Zeppelin",t:"Stairway to Heaven"},
{g:"UK 🇬🇧",a:"Oasis",t:"Don't Look Back in Anger"},{g:"UK 🇬🇧",a:"Adele",t:"Someone Like You"},
{g:"UK 🇬🇧",a:"Coldplay",t:"Fix You"},{g:"UK 🇬🇧",a:"Ed Sheeran",t:"Perfect"},
{g:"Ireland 🇮🇪",a:"Kodaline",t:"All I Want"},{g:"Ireland 🇮🇪",a:"The Script",t:"The Man Who Can't Be Moved"},
{g:"Ireland 🇮🇪",a:"U2",t:"One"},{g:"Ireland 🇮🇪",a:"Sinéad O'Connor",t:"Nothing Compares 2 U"},
{g:"Ireland 🇮🇪",a:"Van Morrison",t:"Have I Told You Lately"},{g:"Ireland 🇮🇪",a:"Enya",t:"Only Time"},
{g:"Ireland 🇮🇪",a:"The Cranberries",t:"Linger"},{g:"Ireland 🇮🇪",a:"Damien Rice",t:"The Blower's Daughter"},
{g:"Ireland 🇮🇪",a:"Hozier",t:"Take Me to Church"},{g:"Ireland 🇮🇪",a:"The Dubliners",t:"The Wild Rover"},
{g:"France 🇫🇷",a:"Édith Piaf",t:"Non, je ne regrette rien"},{g:"France 🇫🇷",a:"Léo Ferré",t:"Avec le temps"},
{g:"France 🇫🇷",a:"Barbara",t:"L'Aigle Noir"},{g:"France 🇫🇷",a:"Django Reinhardt & Stéphane Grappelli",t:"Nuages"},
{g:"France 🇫🇷",a:"Serge Gainsbourg",t:"La Javanaise"},{g:"France 🇫🇷",a:"Indila",t:"Dernière Danse"},
{g:"France 🇫🇷",a:"Maître Gims",t:"Est-ce que tu m'aimes ?"},{g:"France 🇫🇷",a:"M83",t:"Midnight City"},
{g:"France 🇫🇷",a:"Phoenix",t:"If I Ever Feel Better"},{g:"France 🇫🇷",a:"Daft Punk",t:"Something About Us"},
{g:"Belgium 🇧🇪",a:"Stromae & Pomme",t:"Ma Meilleure Ennemie (Arcane)"},{g:"Belgium 🇧🇪",a:"Stromae",t:"Formidable"},
{g:"Belgium 🇧🇪",a:"Jacques Brel",t:"Ne me quitte pas"},{g:"Belgium 🇧🇪",a:"Toots Thielemans",t:"Bluesette"},
{g:"Belgium 🇧🇪",a:"Hooverphonic",t:"Mad About You"},{g:"Belgium 🇧🇪",a:"Angèle",t:"Balance ton quoi"},
{g:"Belgium 🇧🇪",a:"Salvatore Adamo",t:"Tombe la neige"},{g:"Belgium 🇧🇪",a:"Vaya Con Dios",t:"Nah Neh Nah"},
{g:"Belgium 🇧🇪",a:"Selah Sue",t:"Riddim"},{g:"Belgium 🇧🇪",a:"Oscar and the Wolf",t:"The Game"},
{g:"Germany 🇩🇪",a:"Scorpions",t:"Still Loving You"},{g:"Germany 🇩🇪",a:"Nena",t:"Irgendwie, irgendwo, irgendwann"},
{g:"Germany 🇩🇪",a:"Rammstein",t:"Ohne Dich"},{g:"Germany 🇩🇪",a:"Kraftwerk",t:"Das Model"},
{g:"Germany 🇩🇪",a:"Herbert Grönemeyer",t:"Der Weg"},{g:"Germany 🇩🇪",a:"Silbermond",t:"Das Beste"},
{g:"Germany 🇩🇪",a:"Unheilig",t:"Geboren um zu leben"},{g:"Germany 🇩🇪",a:"Revolverheld",t:"Ich lass für dich das Licht an"},
{g:"Germany 🇩🇪",a:"Beethoven",t:"Piano Sonata No. 14 (Moonlight)"},{g:"Germany 🇩🇪",a:"Cassandra Steen",t:"Stadt"},
{g:"Netherlands 🇳🇱",a:"Golden Earring",t:"Radar Love"},{g:"Netherlands 🇳🇱",a:"Shocking Blue",t:"Venus"},
{g:"Netherlands 🇳🇱",a:"Anouk",t:"Nobody's Wife"},{g:"Netherlands 🇳🇱",a:"Within Temptation",t:"Stand My Ground"},
{g:"Netherlands 🇳🇱",a:"André Hazes",t:"Zij gelooft in mij"},{g:"Netherlands 🇳🇱",a:"Marco Borsato",t:"Dromen zijn bedrog"},
{g:"Netherlands 🇳🇱",a:"Racoon",t:"Love You More"},{g:"Netherlands 🇳🇱",a:"Caro Emerald",t:"Back It Up"},
{g:"Netherlands 🇳🇱",a:"Duncan Laurence",t:"Arcade"},{g:"Netherlands 🇳🇱",a:"2 Unlimited",t:"No Limit"},
{g:"Sweden 🇸🇪",a:"Roxette",t:"Listen to Your Heart"},{g:"Sweden 🇸🇪",a:"ABBA",t:"The Winner Takes It All"},
{g:"Sweden 🇸🇪",a:"Avicii",t:"The Nights"},{g:"Sweden 🇸🇪",a:"Europe",t:"Carrie"},
{g:"Sweden 🇸🇪",a:"Kent",t:"Om du var här"},{g:"Sweden 🇸🇪",a:"Lykke Li",t:"I Follow Rivers"},
{g:"Sweden 🇸🇪",a:"First Aid Kit",t:"Emmylou"},{g:"Sweden 🇸🇪",a:"Robyn",t:"Dancing On My Own"},
{g:"Sweden 🇸🇪",a:"The Cardigans",t:"My Favourite Game"},{g:"Sweden 🇸🇪",a:"Zara Larsson",t:"Symphony"},
{g:"Norway 🇳🇴",a:"a-ha",t:"Take On Me"},{g:"Norway 🇳🇴",a:"a-ha",t:"Summer Moved On"},
{g:"Norway 🇳🇴",a:"a-ha",t:"Hunting High and Low"},{g:"Norway 🇳🇴",a:"Aurora",t:"Runaway"},
{g:"Norway 🇳🇴",a:"Sissel Kyrkjebø",t:"Eg Veit I Himmerik Ei Borg"},{g:"Norway 🇳🇴",a:"Wardruna",t:"Fehu"},
{g:"Norway 🇳🇴",a:"Röyksopp",t:"Eple"},{g:"Norway 🇳🇴",a:"Kings of Convenience",t:"Homesick"},
{g:"Norway 🇳🇴",a:"Sigrid",t:"Strangers"},{g:"Norway 🇳🇴",a:"Kygo & Conrad Sewell",t:"Firestone"},
{g:"Italy 🇮🇹",a:"Fabrizio De André",t:"La Guerra di Piero"},{g:"Italy 🇮🇹",a:"Luciano Pavarotti",t:"Nessun Dorma"},
{g:"Italy 🇮🇹",a:"Ennio Morricone",t:"Gabriel's Oboe"},{g:"Italy 🇮🇹",a:"Mina",t:"Se Telefonando"},
{g:"Italy 🇮🇹",a:"Lucio Dalla",t:"Caruso"},{g:"Italy 🇮🇹",a:"Andrea Bocelli",t:"Con te partirò"},
{g:"Italy 🇮🇹",a:"Måneskin",t:"The Loneliest"},{g:"Italy 🇮🇹",a:"Ludovico Einaudi",t:"Nuvole Bianche"},
{g:"Italy 🇮🇹",a:"Zucchero & Paul Young",t:"Senza una donna"},{g:"Italy 🇮🇹",a:"Toto Cutugno",t:"L'Italiano"},
{g:"Spain 🇪🇸",a:"Paco de Lucía",t:"Entre Dos Aguas"},{g:"Spain 🇪🇸",a:"Camarón de la Isla",t:"Leyenda del Tiempo"},
{g:"Spain 🇪🇸",a:"Enrique Morente",t:"Pequeño Vals Vienés"},{g:"Spain 🇪🇸",a:"Andrés Segovia",t:"Asturias (Leyenda)"},
{g:"Spain 🇪🇸",a:"Lole y Manuel",t:"Tu Mirá"},{g:"Spain 🇪🇸",a:"Joaquín Sabina",t:"19 días y 500 noches"},
{g:"Spain 🇪🇸",a:"Mecano",t:"Hijo de la Luna"},{g:"Spain 🇪🇸",a:"Alejandro Sanz",t:"Corazón Partío"},
{g:"Spain 🇪🇸",a:"Pablo Alborán",t:"Solamente Tú"},{g:"Spain 🇪🇸",a:"Enrique Iglesias",t:"Héroe"},
{g:"Portugal 🇵🇹",a:"Amália Rodrigues",t:"Barco Negro"},{g:"Portugal 🇵🇹",a:"Mariza",t:"Gente da Minha Terra"},
{g:"Portugal 🇵🇹",a:"Madredeus",t:"O Pastor"},{g:"Portugal 🇵🇹",a:"Carlos do Carmo",t:"Canoas do Tejo"},
{g:"Portugal 🇵🇹",a:"José Afonso",t:"Grândola, Vila Morena"},{g:"Portugal 🇵🇹",a:"Ana Moura",t:"Desfado"},
{g:"Portugal 🇵🇹",a:"Dulce Pontes",t:"Canção do Mar"},{g:"Portugal 🇵🇹",a:"António Zambujo",t:"Estranha Forma de Vida"},
{g:"Portugal 🇵🇹",a:"Cuca Roseta",t:"Meu Amor de Longe"},{g:"Greece 🇬🇷",a:"Eleftheria Arvanitaki",t:"Dinata Dinata"},
{g:"Greece 🇬🇷",a:"Nana Mouskouri",t:"The White Rose of Athens"},{g:"Greece 🇬🇷",a:"Demis Roussos",t:"Forever and Ever"},
{g:"Greece 🇬🇷",a:"Vangelis",t:"Chariots of Fire"},{g:"Greece 🇬🇷",a:"Yanni",t:"One Man's Dream"},
{g:"Greece 🇬🇷",a:"Mikis Theodorakis",t:"Zorba's Dance"},{g:"Greece 🇬🇷",a:"Alkistis Protopsalti",t:"To Tango tis Nefelis"},
{g:"Greece 🇬🇷",a:"Melina Mercouri",t:"Never on Sunday"},{g:"Greece 🇬🇷",a:"Vangelis",t:"Blade Runner Blues"},
{g:"Greece 🇬🇷",a:"Giorgos Dalaras",t:"Kaigomai Kaigomai"},{g:"Russia 🇷🇺",a:"Би-2",t:"Полковнику никто не пишет"},
{g:"Russia 🇷🇺",a:"ДДТ",t:"Что такое осень"},{g:"Russia 🇷🇺",a:"Владимир Высоцкий",t:"Кони привередливые"},
{g:"Russia 🇷🇺",a:"Булат Окуджава",t:"Надежды маленький оркестрик"},{g:"Russia 🇷🇺",a:"Земфира",t:"Хочешь?"},
{g:"Russia 🇷🇺",a:"Мумий Тролль",t:"Медведица"},{g:"Russia 🇷🇺",a:"Сплин",t:"Выхода нет"},
{g:"Russia 🇷🇺",a:"Алла Пугачёва",t:"Миллион алых роз"},{g:"Russia 🇷🇺",a:"Кино (Виктор Цой)",t:"Группа крови"},
{g:"Russia 🇷🇺",a:"A'Studio",t:"Улетаю"},{g:"Ukraine 🇺🇦",a:"Океан Ельзи",t:"Без бою"},
{g:"Ukraine 🇺🇦",a:"Океан Ельзи",t:"Не твоя війна"},{g:"Ukraine 🇺🇦",a:"ДахаБраха",t:"Весна"},
{g:"Ukraine 🇺🇦",a:"Ruslana",t:"Wild Dances"},{g:"Ukraine 🇺🇦",a:"Jamala",t:"1944"},
{g:"Ukraine 🇺🇦",a:"Go_A",t:"Шум"},{g:"Ukraine 🇺🇦",a:"Boombox",t:"Вахтёрам"},
{g:"Ukraine 🇺🇦",a:"KAZKA",t:"Plakała"},{g:"Ukraine 🇺🇦",a:"Skryabin",t:"Стоп"},
{g:"Ukraine 🇺🇦",a:"Jerry Heil",t:"Вільна"},{g:"Poland 🇵🇱",a:"Czesław Niemen",t:"Dziwny jest ten świat"},
{g:"Poland 🇵🇱",a:"Marek Grechuta",t:"Dni, których nie znamy"},{g:"Poland 🇵🇱",a:"Anna Maria Jopek",t:"Na dłoni"},
{g:"Poland 🇵🇱",a:"Dawid Podsiadło",t:"Małomiasteczkowy"},{g:"Poland 🇵🇱",a:"Kwiat Jabłoni",t:"Dziś późno pójdę spać"},
{g:"Poland 🇵🇱",a:"Sanah",t:"Szampan"},{g:"Poland 🇵🇱",a:"Stare Dobre Małżeństwo",t:"Bieszczadzkie anioły"},
{g:"Poland 🇵🇱",a:"Republika",t:"Świat na odwrót"},{g:"Poland 🇵🇱",a:"Kayah & Goran Bregović",t:"Prawy do lewego"},
{g:"Poland 🇵🇱",a:"Vito Bambino",t:"Fiołkowe Pole"},{g:"USA 🇺🇸",a:"John Coltrane",t:"Acknowledgement (A Love Supreme)"},
{g:"USA 🇺🇸",a:"Billie Holiday",t:"Strange Fruit"},{g:"USA 🇺🇸",a:"Nina Simone",t:"Feeling Good"},
{g:"USA 🇺🇸",a:"Aretha Franklin",t:"Ain't No Way"},{g:"USA 🇺🇸",a:"Whitney Houston",t:"I Will Always Love You"},
{g:"USA 🇺🇸",a:"Jeff Buckley",t:"Hallelujah"},{g:"USA 🇺🇸",a:"Bob Dylan",t:"Blowin' in the Wind"},
{g:"USA 🇺🇸",a:"Linkin Park",t:"In the End"},{g:"USA 🇺🇸",a:"Imagine Dragons",t:"Enemy"},
{g:"USA 🇺🇸",a:"Bruno Mars & Lady Gaga",t:"Die With a Smile"},{g:"Canada 🇨🇦",a:"The Weeknd",t:"Call Out My Name"},
{g:"Canada 🇨🇦",a:"Céline Dion",t:"Pour que tu m'aimes encore"},{g:"Canada 🇨🇦",a:"Céline Dion",t:"My Heart Will Go On"},
{g:"Canada 🇨🇦",a:"Joni Mitchell",t:"A Case of You"},{g:"Canada 🇨🇦",a:"Leonard Cohen",t:"Dance Me to the End of Love"},
{g:"Canada 🇨🇦",a:"Neil Young",t:"Heart of Gold"},{g:"Canada 🇨🇦",a:"Bryan Adams",t:"(Everything I Do) I Do It for You"},
{g:"Canada 🇨🇦",a:"Michael Bublé",t:"Home"},{g:"Canada 🇨🇦",a:"Sarah McLachlan",t:"Angel"},
{g:"Canada 🇨🇦",a:"Alanis Morissette",t:"Ironic"},{g:"Jamaica 🇯🇲",a:"Bob Marley",t:"Redemption Song"},
{g:"Jamaica 🇯🇲",a:"Bob Marley",t:"No Woman, No Cry"},{g:"Jamaica 🇯🇲",a:"Jimmy Cliff",t:"Many Rivers to Cross"},
{g:"Jamaica 🇯🇲",a:"Toots & the Maytals",t:"54-46 Was My Number"},{g:"Jamaica 🇯🇲",a:"Peter Tosh",t:"Equal Rights"},
{g:"Jamaica 🇯🇲",a:"Burning Spear",t:"Marcus Garvey"},{g:"Jamaica 🇯🇲",a:"Dennis Brown",t:"Money in My Pocket"},
{g:"Jamaica 🇯🇲",a:"Gregory Isaacs",t:"Night Nurse"},{g:"Jamaica 🇯🇲",a:"Culture",t:"Two Sevens Clash"},
{g:"Jamaica 🇯🇲",a:"Desmond Dekker",t:"Israelites"},{g:"Cuba 🇨🇺",a:"Compay Segundo",t:"Chan Chan"},
{g:"Cuba 🇨🇺",a:"Ibrahim Ferrer",t:"Bruca Maniguá"},{g:"Cuba 🇨🇺",a:"Omara Portuondo",t:"Veinte Años"},
{g:"Cuba 🇨🇺",a:"Silvio Rodríguez",t:"Ojalá"},{g:"Cuba 🇨🇺",a:"Chucho Valdés",t:"Mambo Influenciado"},
{g:"Cuba 🇨🇺",a:"Beny Moré",t:"Como Fue"},{g:"Cuba 🇨🇺",a:"Celia Cruz",t:"La Vida es un Carnaval"},
{g:"Cuba 🇨🇺",a:"Pablo Milanés",t:"Yolanda"},{g:"Cuba 🇨🇺",a:"Buena Vista Social Club",t:"El Cuarto de Tula"},
{g:"Cuba 🇨🇺",a:"Polo Montañez",t:"Un montón de estrellas"},{g:"Mexico 🇲🇽",a:"Chavela Vargas",t:"La Llorona"},
{g:"Mexico 🇲🇽",a:"Lola Beltrán",t:"Cucurrucucú Paloma"},{g:"Mexico 🇲🇽",a:"Agustín Lara",t:"Granada"},
{g:"Mexico 🇲🇽",a:"José Alfredo Jiménez",t:"El Rey"},{g:"Mexico 🇲🇽",a:"Los Panchos & Eydie Gormé",t:"Bésame Mucho"},
{g:"Mexico 🇲🇽",a:"Juan Gabriel",t:"Amor Eterno"},{g:"Mexico 🇲🇽",a:"Vicente Fernández",t:"Volver, Volver"},
{g:"Mexico 🇲🇽",a:"Maná",t:"Mariposa Traicionera"},{g:"Mexico 🇲🇽",a:"Café Tacvba",t:"Eres"},
{g:"Mexico 🇲🇽",a:"Luis Miguel",t:"La Incondicional"},{g:"Brazil 🇧🇷",a:"Elis Regina & Tom Jobim",t:"Águas de Março"},
{g:"Brazil 🇧🇷",a:"João Gilberto",t:"Chega de Saudade"},{g:"Brazil 🇧🇷",a:"Caetano Veloso",t:"Terra"},
{g:"Brazil 🇧🇷",a:"Milton Nascimento",t:"Travessia"},{g:"Brazil 🇧🇷",a:"Baden Powell & Vinicius de Moraes",t:"Canto de Ossanha"},
{g:"Brazil 🇧🇷",a:"Djavan",t:"Flor de Lis"},{g:"Brazil 🇧🇷",a:"Roberto Carlos",t:"Amigo"},
{g:"Brazil 🇧🇷",a:"Tim Maia",t:"O Caminho do Bem"},{g:"Brazil 🇧🇷",a:"Chico Buarque",t:"Construção"},
{g:"Brazil 🇧🇷",a:"Elis Regina",t:"Madalena"},{g:"Argentina 🇦🇷",a:"Carlos Gardel",t:"Volver"},
{g:"Argentina 🇦🇷",a:"Astor Piazzolla",t:"Adiós Nonino"},{g:"Argentina 🇦🇷",a:"Astor Piazzolla",t:"Oblivion"},
{g:"Argentina 🇦🇷",a:"Mercedes Sosa",t:"Alfonsina y el Mar"},{g:"Argentina 🇦🇷",a:"Atahualpa Yupanqui",t:"Los Hermanos"},
{g:"Argentina 🇦🇷",a:"Luis Alberto Spinetta",t:"Barro Tal Vez"},{g:"Argentina 🇦🇷",a:"Charly García",t:"Seminare"},
{g:"Argentina 🇦🇷",a:"Fito Páez",t:"11 y 6"},{g:"Argentina 🇦🇷",a:"Gustavo Cerati",t:"Crimen"},
{g:"Argentina 🇦🇷",a:"Soda Stereo",t:"De Música Ligera"},{g:"Colombia 🇨🇴",a:"Juanes",t:"Fotografía"},
{g:"Colombia 🇨🇴",a:"Shakira",t:"Underneath Your Clothes"},{g:"Colombia 🇨🇴",a:"Carlos Vives",t:"Fruta Fresca"},
{g:"Colombia 🇨🇴",a:"Fonseca",t:"Te Mando Flores"},{g:"Colombia 🇨🇴",a:"Bacilos",t:"Caraluna"},
{g:"Colombia 🇨🇴",a:"Joe Arroyo",t:"La Rebelión"},{g:"Colombia 🇨🇴",a:"Bomba Estéreo",t:"To My Love"},
{g:"Colombia 🇨🇴",a:"Diomedes Díaz",t:"Tres canciones"},{g:"Colombia 🇨🇴",a:"Grupo Niche",t:"Cali Pachanguero"},
{g:"Colombia 🇨🇴",a:"ChocQuibTown",t:"De Donde Vengo Yo"},{g:"Australia 🇦🇺",a:"Sia",t:"Chandelier"},
{g:"Australia 🇦🇺",a:"Gotye & Kimbra",t:"Somebody That I Used to Know"},{g:"Australia 🇦🇺",a:"Tame Impala",t:"The Less I Know the Better"},
{g:"Australia 🇦🇺",a:"Crowded House",t:"Don't Dream It's Over"},{g:"Australia 🇦🇺",a:"Kylie Minogue",t:"Can't Get You Out of My Head"},
{g:"Australia 🇦🇺",a:"Dean Lewis",t:"Be Alright"},{g:"Australia 🇦🇺",a:"Vance Joy",t:"Riptide"},
{g:"Australia 🇦🇺",a:"The Kid LAROI & Justin Bieber",t:"Stay"},{g:"Australia 🇦🇺",a:"Nick Cave & The Bad Seeds",t:"Into My Arms"},
{g:"Australia 🇦🇺",a:"Empire of the Sun",t:"Walking on a Dream"}
];
const IDS = {"Ebi|Shab-e Niloofari": "JVOW8DNHZR8", "Siavash Ghomeyshi|Jazireh": "eq4NHCr8PaE", "Faramarz Aslani|Age Ye Rooz": "GgqmpRa2nig", "Dariush|Shab az Mahtab Sar Mire": "A-1vHRMywew", "Mohsen Chavoshi|Ghahveye Ghajari": "mQfK6lXYQ6I", "Mohsen Yeganeh|Beyte Akhar": "XfOHghVrhHk", "Ehaam|Bezan Baran": "IYWni3wNMDY", "Hayedeh|Siah Cheshmoon": "jcxDdhFvMxc", "Homayoun Shajarian|Koli": "gHs77boDUk8", "Sirvan Khosravi|Ghabe Akse Khali": "ZBnI5fPcASI", "Annika|Luk Mig Ind": "s7G-uoHzW78", "Twenty One Pilots|The Line (Arcane)": "E2Rj2gQAyPA", "Imagine Dragons|Natural": "0I647GU3Jsc", "Imagine Dragons|Radioactive": "w3viBe2Q0P8", "Lady Gaga|Always Remember Us This Way": "5vheNbQlsyU", "Nusrat Fateh Ali Khan|Allah Hoo": "Nqwmh4WXMmo", "Nusrat Fateh Ali Khan|Ye Jo Halka Halka Suroor Hai": "TF_cOANSeJ8", "Mehdi Hassan|Ranjish Hi Sahi": "Xc6uwbXpmUY", "Ghulam Ali|Chupke Chupke Raat Din": "MWjaK_nW72E", "Abida Parveen|Tere Ishq Nachaya": "7-wYC6bGqQw", "Farida Khanum|Aaj Jaan Ki Zid Na Karo": "KDJL2FyRDeA", "Atif Aslam|Tajdar-e Haram (Coke Studio)": "a18py61_F_w", "Rahat Fateh Ali Khan & Momina|Afreen Afreen (Coke Studio)": "kw4tT7SCmaY", "Vital Signs|Dil Dil Pakistan": "rMlKSqgNHNU", "Nazia Hassan|Aap Jaisa Koi": "mBVArtrjO1E", "A.R. Rahman|Kun Faya Kun": "T94PHkuydcw", "A.R. Rahman|Tere Bina": "9JDSGhhiOwI", "Lata Mangeshkar|Lag Ja Gale": "y2fgw1Oqz28", "Kishore Kumar|O Mere Dil Ke Chain": "-Px0efU00uQ", "Jagjit Singh|Hothon Se Chhu Lo Tum": "X0gB9jcgXxg", "Shreya Ghoshal|Teri Ore": "i5--KP6U3y4", "Shankar Mahadevan|Breathless": "nWeax5joZFw", "Sukhwinder Singh|Chaiyya Chaiyya": "Pxsd0cOCf00", "Asha Bhosle|Piya Tu Ab To Aaja": "VXzBcOALekA", "A.R. Rahman|Agar Tum Saath Ho": "sK7riqg2mr4", "Sirusho|PreGomesh": "wxxnY-QTUGU", "Aram Khachaturian|Adagio from Spartacus": "fnFeXa0nGao", "Charles Aznavour|La Bohème": "fVfnEyLOkrM", "Aram Mp3|Not Alone": "ChkJpnOgIwQ", "Iveta Mukuchyan|LoveWave": "l7m3wOGhEvE", "Tigran Hamasyan|Levitation 21": "Db3dHajCRRY", "Djivan Gasparyan|Melancholy": "5hOhEh4KrBo", "Maléna|Qami": "LWh3927tVhU", "Nino Katamadze|Blue Smoke": "gaoFWAxlW5k", "Katie Melua|Nine Million Bicycles": "rrPUJsZQSkw", "Sopho Nizharadze|Shine": "y5yTMGxFiPw", "Dimash Kudaibergen|SOS": "AUARjexCTlQ", "Dimash Kudaibergen|Daididau": "BTXIxXPee3U", "Zhanar Dugalova|Izin Korem": "phIQuuz4hdQ", "MuzArt|Senimen": "Rb0UmrCXxVA", "Dimash Kudaibergen|Konyldym": "Xlx2pmO3JzU", "Kenshi Yonezu|Lemon": "SX_ViT4Ra7k", "Official HIGE DANdism|Pretender": "TQ8WlA2GXbk", "Hibari Misora|Kawa no Nagare no Yō ni": "_JPKop-dYJ8", "Ryuichi Sakamoto|Merry Christmas Mr. Lawrence": "jElCDsfptVU", "Ryo Fukui|Early Summer": "F5EFsUU7RRA", "YOASOBI|Yoru ni Kakeru": "by4SYYWlhEs", "Utada Hikaru|First Love": "jhrhHtFfIgs", "X Japan|Endless Rain": "QhOFg_3RV5Q", "Kim Bum-soo|Bo Go Ship Da (I Miss You)": "c0xko6pVoeY", "Lee Sun-hee|Fate (인연)": "bPpgc9wrat0", "Im Jae-beom|As This Night Passes": "WtWzUFWKLRM", "Cho Yong-pil|Come Back to Busan Port": "tBtHLDObsx0", "Shin Joong Hyun|Jasmine": "jjxZ7wIwiHE", "Lee Moon-sae|Gwanghwamun Sonata": "wJmFkK7MBI0", "Younha|Event Horizon": "73V3xrfiYMo", "IU|Through the Night": "HEYOsR1DlWE", "Position|I Love You": "9d4-lgpbwoA", "Teresa Teng|The Moon Represents My Heart": "bv_cEeDlop0", "Jay Chou|Qing Hua Ci": "Z8Mqw0b9ADs", "Faye Wong|Legend (传奇)": "kSeevdvySHg", "Jonathan Lee|Hill (山丘)": "rVEMTxg_LrU", "Eason Chan|Ten Years (十年)": "BqbvK2I_Baw", "Cui Jian|Nothing to My Name (一无所有)": "m7uk0-vlpP0", "Freddie Aguilar|Anak": "ibmh64itn1M", "Eraserheads|Ang Huling El Bimbo": "lajnSJZpI34", "Rivermaya|214": "d59MC-PEJK0", "Bamboo|Noypi": "JLvum0chagg", "Sharon Cuneta|Kahit Maputi Na Ang Buhok Ko": "f2uooyHYh1c", "Rey Valera|Kung Kailangan Mo Ako": "A0nGIoypfbM", "Regine Velasquez|On the Wings of Love": "glEJS3lld4g", "Basil Valdez|Ngayon at Kailanman": "jtIH1U2TclM", "Lea Salonga|Reflection": "9W9em1zhk5s", "VST Company|Awitin Mo at Isasayaw Ko": "CAHsClyYRt8", "Burna Boy|Last Last": "421w1j87fEM", "The Beatles|A Day in the Life": "usNsCeOV4GM", "David Bowie|Life on Mars?": "AZKcl4-tcuo", "Queen|Bohemian Rhapsody": "fJ9rUzIMcZQ", "Pink Floyd|Wish You Were Here": "K6qj09OHvjw", "Kate Bush|This Woman's Work": "UXzx--YefD8", "Led Zeppelin|Stairway to Heaven": "QkF3oxziUI4", "Oasis|Don't Look Back in Anger": "cmpRLQZkTb8", "Adele|Someone Like You": "hLQl3WQQoQ0", "Coldplay|Fix You": "k4V3Mo61fJM", "Ed Sheeran|Perfect": "2Vv-BfVoq4g", "Kodaline|All I Want": "NRhmmqsZIpw", "The Script|The Man Who Can't Be Moved": "gS9o1FAszdk", "U2|One": "ftjEcrrf7r0", "Sinéad O'Connor|Nothing Compares 2 U": "0-EF60neguk", "Van Morrison|Have I Told You Lately": "J789GId1kaY", "Enya|Only Time": "7wfYIMyS_dI", "The Cranberries|Linger": "G6Kspj3OO0s", "Damien Rice|The Blower's Daughter": "5YXVMCHG-Nk", "Hozier|Take Me to Church": "MYSVMgRr6pw", "The Dubliners|The Wild Rover": "9iRRvjjHDkw", "Édith Piaf|Non, je ne regrette rien": "Q3Kvu6Kgp88", "Léo Ferré|Avec le temps": "ZH7dG0qyzyg", "Barbara|L'Aigle Noir": "kDqtyruAd4Q", "Django Reinhardt & Stéphane Grappelli|Nuages": "2T2_pk1iwQM", "Serge Gainsbourg|La Javanaise": "V6gjzNm6dA0", "Indila|Dernière Danse": "K5KAc5CoCuk", "Maître Gims|Est-ce que tu m'aimes ?": "6TpyRE_juyA", "M83|Midnight City": "dX3k_QDnzHE", "Phoenix|If I Ever Feel Better": "LZlGqWpCF58", "Daft Punk|Something About Us": "em0MknB6wFo", "Stromae & Pomme|Ma Meilleure Ennemie (Arcane)": "j-RpvIuazmc", "Stromae|Formidable": "S_xH7noaqTA", "Jacques Brel|Ne me quitte pas": "oR_SZR_tmxM", "Toots Thielemans|Bluesette": "yKnG_9q4crA", "Hooverphonic|Mad About You": "xVKGXgHDMvQ", "Angèle|Balance ton quoi": "Hi7Rx3En7-k", "Salvatore Adamo|Tombe la neige": "_64nc_NLE_I", "Vaya Con Dios|Nah Neh Nah": "7LUm-E4GPU8", "Selah Sue|Riddim": "-IunmW3wI5Q", "Oscar and the Wolf|The Game": "yfHSgGrcndc", "Scorpions|Still Loving You": "7pOr3dBFAeY", "Nena|Irgendwie, irgendwo, irgendwann": "oMHLkcc9I9c", "Rammstein|Ohne Dich": "LIPc1cfS-oQ", "Kraftwerk|Das Model": "OQIYEPe6DWY", "Herbert Grönemeyer|Der Weg": "xSWJBClrmgo", "Silbermond|Das Beste": "LyYAQHDMqfA", "Unheilig|Geboren um zu leben": "1YOovPkiMrk", "Revolverheld|Ich lass für dich das Licht an": "oGhdsruanPg", "Beethoven|Piano Sonata No. 14 (Moonlight)": "4Tr0otuiQuU", "Cassandra Steen|Stadt": "ltQNeihjqB0", "Golden Earring|Radar Love": "aRlSHG5hRY4", "Shocking Blue|Venus": "8LhkyyCvUHk", "Anouk|Nobody's Wife": "3RaHTDNude4", "Within Temptation|Stand My Ground": "98xh5Hb9QAM", "André Hazes|Zij gelooft in mij": "4GH6PS4RYJw", "Marco Borsato|Dromen zijn bedrog": "3tcHzIcrdms", "Racoon|Love You More": "2j4MWZevjYw", "Caro Emerald|Back It Up": "jo1cyl0QbWo", "Duncan Laurence|Arcade": "51u5fnyrGj4", "2 Unlimited|No Limit": "7kmEEkECFQw", "Roxette|Listen to Your Heart": "yCC_b5WHLX0", "ABBA|The Winner Takes It All": "92cwKCU8Z5c", "Avicii|The Nights": "UtF6Jej8yb4", "Europe|Carrie": "KmWE9UBFwtY", "Kent|Om du var här": "H_PmA9gIbZM", "Lykke Li|I Follow Rivers": "uY4q6I-dzE8", "First Aid Kit|Emmylou": "PC57z-oDPLs", "Robyn|Dancing On My Own": "CcNo07Xp8aQ", "The Cardigans|My Favourite Game": "u9WgtlgGAgs", "Zara Larsson|Symphony": "1DxxjGsRWYs", "a-ha|Take On Me": "djV11Xbc914", "a-ha|Summer Moved On": "oVl4qvHuY8g", "a-ha|Hunting High and Low": "s6VaeFCxta8", "Aurora|Runaway": "d_HlPboLRL8", "Sissel Kyrkjebø|Eg Veit I Himmerik Ei Borg": "wNrBcYGd4GE", "Wardruna|Fehu": "H6RCY-G-NlA", "Röyksopp|Eple": "tf_ieWnu-SE", "Kings of Convenience|Homesick": "uUn-R9pxGAs", "Sigrid|Strangers": "cIriwVhRPVA", "Kygo & Conrad Sewell|Firestone": "9Sc-ir2UwGU", "Fabrizio De André|La Guerra di Piero": "KoYw0LHEWLM", "Luciano Pavarotti|Nessun Dorma": "cWc7vYjgnTs", "Ennio Morricone|Gabriel's Oboe": "s7w-IeNR9ko", "Mina|Se Telefonando": "x6fpSiE953w", "Lucio Dalla|Caruso": "I84FCXqA1Vk", "Andrea Bocelli|Con te partirò": "TdWEhMOrRpQ", "Måneskin|The Loneliest": "odWKEfp2QMY", "Ludovico Einaudi|Nuvole Bianche": "VUCI-1vIbUo", "Zucchero & Paul Young|Senza una donna": "V69vs8JmXYM", "Toto Cutugno|L'Italiano": "TYtdYslLY9I", "Paco de Lucía|Entre Dos Aguas": "2oyhlad64-s", "Camarón de la Isla|Leyenda del Tiempo": "MrUWtOtfwDw", "Enrique Morente|Pequeño Vals Vienés": "D9VixUcNIeY", "Andrés Segovia|Asturias (Leyenda)": "lCeebWgjrrU", "Lole y Manuel|Tu Mirá": "SudbXjfXpJ4", "Joaquín Sabina|19 días y 500 noches": "qahBeZB1g54", "Mecano|Hijo de la Luna": "OwGG5fX7bxY", "Alejandro Sanz|Corazón Partío": "ZMUqIoDtSwc", "Pablo Alborán|Solamente Tú": "F0rwOsAteXM", "Enrique Iglesias|Héroe": "koJlIGDImiU", "Amália Rodrigues|Barco Negro": "DVFOUMJXdU8", "Mariza|Gente da Minha Terra": "S2Ip-uUhaoI", "Madredeus|O Pastor": "kIbzGDPdeog", "Carlos do Carmo|Canoas do Tejo": "d1k0EFPUEZE", "José Afonso|Grândola, Vila Morena": "gaLWqy4e7ls", "Ana Moura|Desfado": "V3Nv93m20nI", "Dulce Pontes|Canção do Mar": "v_2fyB4dj4U", "António Zambujo|Estranha Forma de Vida": "VGgIlLfVEmQ", "Cuca Roseta|Meu Amor de Longe": "DZAzhEOkpN8", "Eleftheria Arvanitaki|Dinata Dinata": "6Aj2ah4H5dU", "Nana Mouskouri|The White Rose of Athens": "mRpMCG5Wjck", "Demis Roussos|Forever and Ever": "F3vCB3YBMUo", "Vangelis|Chariots of Fire": "8a-HfNE3EIo", "Yanni|One Man's Dream": "eClhtAge0IY", "Mikis Theodorakis|Zorba's Dance": "GIoHp6mr9Vg", "Alkistis Protopsalti|To Tango tis Nefelis": "hG3aruAV2sg", "Melina Mercouri|Never on Sunday": "o9ATOp7GnTA", "Vangelis|Blade Runner Blues": "RScZrvTebeA", "Giorgos Dalaras|Kaigomai Kaigomai": "aXJQmTSptCc", "Би-2|Полковнику никто не пишет": "1u7WN2zBEDc", "ДДТ|Что такое осень": "LvaYk-phy14", "Владимир Высоцкий|Кони привередливые": "4hQQ4i7bf4U", "Булат Окуджава|Надежды маленький оркестрик": "C7Od0wuvpEE", "Земфира|Хочешь?": "xpJ_fYyAeYk", "Мумий Тролль|Медведица": "3uDFkM8FH_E", "Сплин|Выхода нет": "SDTD4pL0mLc", "Алла Пугачёва|Миллион алых роз": "BQV0TrlB0gA", "Кино (Виктор Цой)|Группа крови": "xKpzH5bxYsk", "A'Studio|Улетаю": "Q2RY38t9Dmc", "Океан Ельзи|Без бою": "bbkEVJgrBUs", "Океан Ельзи|Не твоя війна": "eOtEC4wCA40", "ДахаБраха|Весна": "AObDpJ6xQMk", "Ruslana|Wild Dances": "q5TeDlawdz0", "Jamala|1944": "wNECV2h-y58", "Go_A|Шум": "sDeMfL8Ib9A", "Boombox|Вахтёрам": "tnZPDs9qepA", "KAZKA|Plakała": "5Fv19KVVya8", "Skryabin|Стоп": "o5NH2yKhl1M", "Jerry Heil|Вільна": "EzrZRFiJGOY", "Czesław Niemen|Dziwny jest ten świat": "wTjLZwpmufw", "Marek Grechuta|Dni, których nie znamy": "kOzQ7yR7w74", "Anna Maria Jopek|Na dłoni": "0-gUoNGUm88", "Dawid Podsiadło|Małomiasteczkowy": "X2XWBcd5jn0", "Kwiat Jabłoni|Dziś późno pójdę spać": "FWDXwrgdm9w", "Sanah|Szampan": "wl5af6NbG9Y", "Stare Dobre Małżeństwo|Bieszczadzkie anioły": "1fy3dAEAlao", "Republika|Świat na odwrót": "8FhbrTEEIfI", "Kayah & Goran Bregović|Prawy do lewego": "cKF2GjRAUtE", "Vito Bambino|Fiołkowe Pole": "1rTV7DCnF3Y", "John Coltrane|Acknowledgement (A Love Supreme)": "5Pi5ZJZ07ME", "Billie Holiday|Strange Fruit": "-DGY9HvChXk", "Nina Simone|Feeling Good": "oHRNrgDIJfo", "Aretha Franklin|Ain't No Way": "MB1FPOuSVeM", "Whitney Houston|I Will Always Love You": "3JWTaaS7LdU", "Jeff Buckley|Hallelujah": "y8AWFf7EAc4", "Bob Dylan|Blowin' in the Wind": "MMFj8uDubsE", "Linkin Park|In the End": "eVTXPUF4Oz4", "Imagine Dragons|Enemy": "D9G1VOjN_84", "Bruno Mars & Lady Gaga|Die With a Smile": "kPa7bsKwL-c", "The Weeknd|Call Out My Name": "M4ZoCHID9GI", "Céline Dion|Pour que tu m'aimes encore": "AzaTyxMduH4", "Céline Dion|My Heart Will Go On": "9bFHsd3o1w0", "Joni Mitchell|A Case of You": "qAZp5JfDmz4", "Leonard Cohen|Dance Me to the End of Love": "NGorjBVag0I", "Neil Young|Heart of Gold": "c7eB7Wns1-M", "Bryan Adams|(Everything I Do) I Do It for You": "Y0pdQU87dc8", "Michael Bublé|Home": "lbSOLBMUvIE", "Sarah McLachlan|Angel": "i1GmxMTwUgs", "Alanis Morissette|Ironic": "Jne9t8sHpUc", "Bob Marley|Redemption Song": "yv5xonFSC4c", "Bob Marley|No Woman, No Cry": "IT8XvzIfi4U", "Jimmy Cliff|Many Rivers to Cross": "-y9Q7ud7Or0", "Toots & the Maytals|54-46 Was My Number": "1AGngQJf7Rw", "Peter Tosh|Equal Rights": "bOZQZAX4deM", "Burning Spear|Marcus Garvey": "oGN3R49-CAE", "Dennis Brown|Money in My Pocket": "O1VbRLBY6vA", "Gregory Isaacs|Night Nurse": "PvheubKIJz8", "Culture|Two Sevens Clash": "A3PjURr7lb4", "Desmond Dekker|Israelites": "0wSXTN2EfRo", "Compay Segundo|Chan Chan": "mjQrmo37HEs", "Ibrahim Ferrer|Bruca Maniguá": "XjTcKP7JwfY", "Omara Portuondo|Veinte Años": "VRlxgW5yzVU", "Silvio Rodríguez|Ojalá": "u3quFCVY6Ug", "Chucho Valdés|Mambo Influenciado": "YCk_A0y3IYc", "Beny Moré|Como Fue": "p4GggYWjRao", "Celia Cruz|La Vida es un Carnaval": "0nBFWzpWXuM", "Pablo Milanés|Yolanda": "qCwLbI1IMog", "Buena Vista Social Club|El Cuarto de Tula": "gaKKELQWhbs", "Polo Montañez|Un montón de estrellas": "dMmPQ_Wi_Hs", "Chavela Vargas|La Llorona": "mwNBa40y2oA", "Lola Beltrán|Cucurrucucú Paloma": "mRbARIgjgss", "Agustín Lara|Granada": "nR6CIYgEJbE", "José Alfredo Jiménez|El Rey": "ZipzeNiBe_E", "Los Panchos & Eydie Gormé|Bésame Mucho": "MY0fuEfBmD4", "Juan Gabriel|Amor Eterno": "RgKqxLAhRKE", "Vicente Fernández|Volver, Volver": "NPg_jbGYzgA", "Maná|Mariposa Traicionera": "av3wkasS-WQ", "Café Tacvba|Eres": "98Akpf1ph2o", "Luis Miguel|La Incondicional": "wOjzo02Tmck", "Elis Regina & Tom Jobim|Águas de Março": "E1tOV7y94DY", "João Gilberto|Chega de Saudade": "yUuJrpP0Mak", "Caetano Veloso|Terra": "wAmtLN4PlLU", "Milton Nascimento|Travessia": "kDe3qOhrJLo", "Baden Powell & Vinicius de Moraes|Canto de Ossanha": "3ueru3eELi4", "Djavan|Flor de Lis": "peR8eOcGA3M", "Roberto Carlos|Amigo": "RSOVVs78wr8", "Tim Maia|O Caminho do Bem": "hwUGJXm02ZQ", "Chico Buarque|Construção": "cMwmBfEtiq0", "Elis Regina|Madalena": "0rFFRI1lq9g", "Carlos Gardel|Volver": "jvHIVqg-g3s", "Astor Piazzolla|Adiós Nonino": "wyRpAat5oz0", "Astor Piazzolla|Oblivion": "dF-IMQzd_Jo", "Mercedes Sosa|Alfonsina y el Mar": "F_FRa9htNiw", "Atahualpa Yupanqui|Los Hermanos": "ZrZIe4zwQZs", "Luis Alberto Spinetta|Barro Tal Vez": "W47hOuQjDag", "Charly García|Seminare": "SskpYGyEDmU", "Fito Páez|11 y 6": "ZweylZ8uiuw", "Gustavo Cerati|Crimen": "uLIs0j2WnlM", "Soda Stereo|De Música Ligera": "T_FkEw27XJ0", "Juanes|Fotografía": "flr8vDQ9Wuc", "Shakira|Underneath Your Clothes": "uwBwKcQ1k84", "Carlos Vives|Fruta Fresca": "in8rFQZsagQ", "Fonseca|Te Mando Flores": "9oLBY9QqTAQ", "Bacilos|Caraluna": "-zgDXIi1uYw", "Joe Arroyo|La Rebelión": "KNcaw0Ye69g", "Bomba Estéreo|To My Love": "THBP1tq49wk", "Diomedes Díaz|Tres canciones": "xcJdmJXqJFw", "Grupo Niche|Cali Pachanguero": "7KxkMLAZlzw", "ChocQuibTown|De Donde Vengo Yo": "yMS4J6Gp6e4", "Sia|Chandelier": "2vjPBrBU-TM", "Gotye & Kimbra|Somebody That I Used to Know": "8UVNT4wvIGY", "Tame Impala|The Less I Know the Better": "sBzrzS1Ag_g", "Crowded House|Don't Dream It's Over": "J9gKyRmic20", "Kylie Minogue|Can't Get You Out of My Head": "c18441Eh_WE", "Dean Lewis|Be Alright": "I0czvJ_jikg", "Vance Joy|Riptide": "uJ_1HMAGb4k", "The Kid LAROI & Justin Bieber|Stay": "yWHrYNP6j4k", "Nick Cave & The Bad Seeds|Into My Arms": "LnHoqHscTKE", "Empire of the Sun|Walking on a Dream": "eimgRedLkkU", "Tems|Free Mind": "mlaTJrQdmiY", "Wizkid|Essence": "jipQpjUA_o8", "Tarkan|Kuzu Kuzu": "NAHRpEqgcL4", "Şebnem Ferah|Sil Baştan": "RExyuxsd-rY", "Teoman|Paramparça": "lh4lMzVcM8A", "Duman|Her Şeyi Yak": "mGr_5vbL80Y", "Sezen Aksu|Kutlama": "N3WhY5mTMXA", "Pinhani|Beni Al": "SwzzDcoM7eg", "Müslüm Gürses|Sen Benim Şarkılarımsın": "TXtgqM73nYA"};
