// Singer vocal ranges — approximate public estimates, MIDI notes (60 = middle C)
// s = singer name as shown · c = country · t = voice type label · lo/hi = MIDI
const SINGERS = [
{n:'Ebi',c:'Iran',t:'baritone',lo:45,hi:70},{n:'Dariush',c:'Iran',t:'baritone',lo:42,hi:67},
{n:'Mohsen Chavoshi',c:'Iran',t:'baritone',lo:42,hi:69},{n:'Mohsen Yeganeh',c:'Iran',t:'tenor',lo:45,hi:71},
{n:'Ehaam',c:'Iran',t:'baritone',lo:43,hi:68},{n:'Homayoun Shajarian',c:'Iran',t:'tenor (classical)',lo:41,hi:72},
{n:'Hayedeh',c:'Iran',t:'contralto',lo:48,hi:81},{n:'Alireza Ghorbani',c:'Iran',t:'baritone',lo:42,hi:67},
{n:'Sirvan Khosravi',c:'Iran',t:'tenor',lo:45,hi:71},{n:'Shadmehr Aghili',c:'Iran',t:'tenor',lo:45,hi:71},
{n:'Morteza Pashaei',c:'Iran',t:'baritone',lo:45,hi:69},{n:'Reza Sadeghi',c:'Iran',t:'baritone',lo:43,hi:66},
{n:'Tarkan',c:'Turkey',t:'tenor',lo:43,hi:67},{n:'Şebnem Ferah',c:'Turkey',t:'mezzo (rock)',lo:45,hi:72},
{n:'Sezen Aksu',c:'Turkey',t:'mezzo',lo:55,hi:72},
{n:'Fairuz',c:'Lebanon',t:'contralto (wide)',lo:45,hi:81},{n:'Umm Kulthum',c:'Egypt',t:'contralto',lo:50,hi:78},
{n:'Abdel Halim Hafez',c:'Egypt',t:'tenor',lo:48,hi:67},{n:'Kathem Al Saher',c:'Iraq',t:'tenor',lo:45,hi:71},
{n:'Amr Diab',c:'Egypt',t:'tenor',lo:45,hi:67},{n:'Asmahan',c:'Egypt/Syria',t:'soprano',lo:55,hi:83},
{n:'Majida El Roumi',c:'Lebanon',t:'soprano',lo:57,hi:73},{n:'Nancy Ajram',c:'Lebanon',t:'mezzo',lo:57,hi:76},
{n:'Nusrat Fateh Ali Khan',c:'Pakistan',t:'tenor (qawwali, wide)',lo:41,hi:81},{n:'Mehdi Hassan',c:'Pakistan',t:'tenor (ghazal)',lo:43,hi:74},
{n:'Ghulam Ali',c:'Pakistan',t:'tenor (ghazal)',lo:45,hi:72},{n:'Abida Parveen',c:'Pakistan',t:'mezzo (sufi)',lo:55,hi:81},
{n:'Atif Aslam',c:'Pakistan',t:'tenor',lo:45,hi:69},{n:'Rahat Fateh Ali Khan',c:'Pakistan',t:'tenor (qawwali)',lo:43,hi:79},
{n:'Lata Mangeshkar',c:'India',t:'soprano',lo:55,hi:83},{n:'Kishore Kumar',c:'India',t:'baritone',lo:45,hi:69},
{n:'Shreya Ghoshal',c:'India',t:'soprano',lo:57,hi:81},
{n:'Kenshi Yonezu',c:'Japan',t:'tenor',lo:45,hi:74},{n:'Kim Bum-soo',c:'South Korea',t:'tenor (power ballad)',lo:43,hi:74},
{n:'IU',c:'South Korea',t:'mezzo',lo:57,hi:76},{n:'Utada Hikaru',c:'Japan/US',t:'mezzo',lo:57,hi:76},
{n:'Teresa Teng',c:'Taiwan',t:'mezzo',lo:55,hi:74},
{n:'Dimash Kudaibergen',c:'Kazakhstan',t:'extreme (6+ octaves)',lo:35,hi:110},
{n:'Zemfira',c:'Russia',t:'mezzo (rock)',lo:45,hi:76},{n:'Vladimir Vysotsky',c:'Russia',t:'bass-baritone',lo:43,hi:62},
{n:'Alla Pugacheva',c:'Russia',t:'mezzo',lo:57,hi:74},{n:'Vitas',c:'Russia',t:'countertenor',lo:52,hi:88},
{n:'Freddie Mercury',c:'UK',t:'tenor (rock)',lo:48,hi:77},{n:'Robert Plant',c:'UK',t:'tenor (rock)',lo:50,hi:84},
{n:'Sting',c:'UK',t:'tenor',lo:48,hi:69},{n:'Bono',c:'Ireland',t:'tenor',lo:47,hi:71},
{n:'Chris Martin',c:'UK',t:'tenor',lo:52,hi:69},{n:'Ed Sheeran',c:'UK',t:'baritenor',lo:45,hi:69},
{n:'Adam Levine',c:'USA',t:'tenor (falsetto)',lo:52,hi:74},{n:'Chester Bennington',c:'USA',t:'tenor (rock)',lo:47,hi:79},
{n:'Chris Cornell',c:'USA',t:'baritenor (wide)',lo:45,hi:93},{n:'Matt Bellamy',c:'UK',t:'tenor (falsetto)',lo:41,hi:83},
{n:'Jeff Buckley',c:'USA',t:'tenor (wide)',lo:40,hi:80},{n:'Kurt Cobain',c:'USA',t:'baritone (grunge)',lo:45,hi:74},
{n:'Stevie Wonder',c:'USA',t:'tenor (wide)',lo:47,hi:79},{n:'Michael Jackson',c:'USA',t:'high tenor',lo:47,hi:86},
{n:'Prince',c:'USA',t:'wide + falsetto',lo:40,hi:88},{n:'Sam Cooke',c:'USA',t:'tenor',lo:48,hi:71},
{n:'Frank Sinatra',c:'USA',t:'baritone',lo:41,hi:65},{n:'Elvis Presley',c:'USA',t:'baritone',lo:41,hi:69},
{n:'Johnny Cash',c:'USA',t:'bass-baritone',lo:40,hi:62},{n:'Bob Dylan',c:'USA',t:'baritone',lo:48,hi:67},
{n:'Leonard Cohen',c:'Canada',t:'bass',lo:37,hi:64},{n:'Bruno Mars',c:'USA',t:'tenor (wide)',lo:48,hi:83},
{n:'Bob Marley',c:'Jamaica',t:'tenor',lo:45,hi:72},{n:'Klaus Meine',c:'Germany',t:'tenor (rock)',lo:45,hi:81},
{n:'Herbert Grönemeyer',c:'Germany',t:'baritone',lo:45,hi:67},
{n:'Whitney Houston',c:'USA',t:'soprano (wide)',lo:53,hi:84},{n:'Mariah Carey',c:'USA',t:'extreme (5+ octaves)',lo:43,hi:103},
{n:'Adele',c:'UK',t:'mezzo',lo:50,hi:80},{n:'Sia',c:'Australia',t:'mezzo (wide)',lo:53,hi:90},
{n:'Beyoncé',c:'USA',t:'mezzo (wide)',lo:57,hi:88},{n:'Lady Gaga',c:'USA',t:'mezzo',lo:56,hi:83},
{n:'Céline Dion',c:'Canada',t:'soprano',lo:49,hi:86},{n:'Aretha Franklin',c:'USA',t:'mezzo (wide)',lo:45,hi:93},
{n:'Nina Simone',c:'USA',t:'contralto',lo:41,hi:79},{n:'Etta James',c:'USA',t:'contralto',lo:45,hi:77},
{n:'Tina Turner',c:'USA',t:'mezzo',lo:43,hi:72},{n:'Janis Joplin',c:'USA',t:'mezzo (rock)',lo:47,hi:77},
{n:'Amy Winehouse',c:'UK',t:'contralto',lo:50,hi:76},{n:'Billie Eilish',c:'USA',t:'whisper mezzo',lo:50,hi:79},
{n:'Sinéad O\'Connor',c:'Ireland',t:'mezzo',lo:55,hi:74},{n:'Enya',c:'Ireland',t:'soprano',lo:55,hi:81},
{n:'Luciano Pavarotti',c:'Italy',t:'tenor (opera)',lo:47,hi:72},{n:'Andrea Bocelli',c:'Italy',t:'tenor',lo:45,hi:70},
{n:'Damiano David',c:'Italy',t:'tenor (rock)',lo:48,hi:71},{n:'Morten Harket',c:'Norway',t:'tenor (wide)',lo:41,hi:81},
{n:'Marie Fredriksson',c:'Sweden',t:'mezzo (rock)',lo:55,hi:79},{n:'Charles Aznavour',c:'France/Armenia',t:'baritone',lo:43,hi:67},
{n:'Édith Piaf',c:'France',t:'mezzo',lo:52,hi:76},
{n:'Shakira',c:'Colombia',t:'mezzo',lo:54,hi:76},{n:'Luis Miguel',c:'Mexico',t:'tenor',lo:47,hi:71},
{n:'Vicente Fernández',c:'Mexico',t:'baritone (ranchero)',lo:45,hi:69},{n:'Juan Gabriel',c:'Mexico',t:'tenor',lo:45,hi:71},
{n:'Mercedes Sosa',c:'Argentina',t:'mezzo (folk)',lo:55,hi:76},{n:'Caetano Veloso',c:'Brazil',t:'baritenor',lo:43,hi:67},
{n:'Djavan',c:'Brazil',t:'tenor (head voice)',lo:45,hi:74},{n:'Roberto Carlos',c:'Brazil',t:'baritone',lo:45,hi:69},
{n:'Enrique Iglesias',c:'Spain',t:'baritenor',lo:45,hi:69},{n:'Alejandro Sanz',c:'Spain',t:'baritenor',lo:43,hi:67},
{n:'Youssou N\'Dour',c:'Senegal',t:'high tenor',lo:54,hi:71},{n:'Salif Keita',c:'Mali',t:'high tenor',lo:60,hi:71},
{n:'Miriam Makeba',c:'South Africa',t:'mezzo',lo:55,hi:76}
];

// Practice songs — vocal line range (approximate), s = singer, a|t = playlist key for the video
const SONGS = [
{s:'Ebi',a:'Ebi',t:'Shab-e Niloofari',lo:50,hi:69},{s:'Dariush',a:'Dariush',t:'Shab az Mahtab Sar Mire',lo:45,hi:67},
{s:'Mohsen Chavoshi',a:'Mohsen Chavoshi',t:'Ghahveye Ghajari',lo:43,hi:68},{s:'Mohsen Yeganeh',a:'Mohsen Yeganeh',t:'Beyte Akhar',lo:47,hi:71},
{s:'Ehaam',a:'Ehaam',t:'Bezan Baran',lo:45,hi:68},{s:'Homayoun Shajarian',a:'Homayoun Shajarian',t:'Koli',lo:43,hi:72},
{s:'Hayedeh',a:'Hayedeh',t:'Siah Cheshmoon',lo:52,hi:79},{s:'Fairuz',a:'Fairuz',t:'Kifak Inta',lo:50,hi:77},
{s:'Umm Kulthum',a:'Umm Kulthum',t:'Al-Atlal',lo:48,hi:78},{s:'Kathem Al Saher',a:'Kathem Al Saher',t:'Zidini Ishqan',lo:45,hi:71},
{s:'Nusrat Fateh Ali Khan',a:'Nusrat Fateh Ali Khan',t:'Allah Hoo',lo:41,hi:76},{s:'Rahat Fateh Ali Khan',a:'Rahat Fateh Ali Khan & Momina',t:'Afreen Afreen (Coke Studio)',lo:43,hi:74},
{s:'Tarkan',a:'Tarkan',t:'Kuzu Kuzu',lo:43,hi:67},{s:'Kenshi Yonezu',a:'Kenshi Yonezu',t:'Lemon',lo:47,hi:74},
{s:'Kim Bum-soo',a:'Kim Bum-soo',t:'Bo Go Ship Da (I Miss You)',lo:45,hi:74},
{s:'Whitney Houston',a:'Whitney Houston',t:'I Will Always Love You',lo:52,hi:81},{s:'Adele',a:'Adele',t:'Someone Like You',lo:55,hi:74},
{s:'Bruno Mars',a:'Bruno Mars & Lady Gaga',t:'Die With a Smile',lo:48,hi:76},{s:'Chris Martin',a:'Coldplay',t:'Fix You',lo:48,hi:72},
{s:'Chester Bennington',a:'Linkin Park',t:'In the End',lo:45,hi:72},{s:'Klaus Meine',a:'Scorpions',t:'Still Loving You',lo:43,hi:77},
{s:'Jeff Buckley',a:'Jeff Buckley',t:'Hallelujah',lo:45,hi:76},{s:'Sinéad O\'Connor',a:'Sinéad O\'Connor',t:'Nothing Compares 2 U',lo:55,hi:74},
{s:'Marie Fredriksson',a:'Roxette',t:'Listen to Your Heart',lo:52,hi:75},{s:'Morten Harket',a:'a-ha',t:'Take On Me',lo:52,hi:81},
{s:'Céline Dion',a:'Céline Dion',t:'My Heart Will Go On',lo:52,hi:77},{s:'Djavan',a:'Djavan',t:'Flor de Lis',lo:45,hi:72},
{s:'Luis Miguel',a:'Luis Miguel',t:'La Incondicional',lo:48,hi:71}
];

const TYPES = [['Bass',40,60],['Baritone',45,64],['Tenor',48,72],['Contralto',53,74],['Mezzo',57,79],['Soprano',60,84]];
